Update master_starwarslegionarmybuilder-webapp.yml

diff --git a/.github/workflows/master_starwarslegionarmybuilder-webapp.yml b/.github/workflows/master_starwarslegionarmybuilder-webapp.yml
--- a/.github/workflows/master_starwarslegionarmybuilder-webapp.yml
+++ b/.github/workflows/master_starwarslegionarmybuilder-webapp.yml
@@ -58,10 +58,10 @@ jobs:
           echo "Listing all files in the current directory:"
           dir
 
-      - name: List contents of downloaded artifact (debugging)
+      - name: List contents of the downloaded artifact (debugging)
         run: |
           echo "Listing contents of the downloaded artifact:"
-          dir ./myapp || echo "Directory not found"
+          dir D:\a\_temp || echo "Directory not found"
 
       - name: Login to Azure
         uses: azure/login@v2
@@ -76,4 +76,4 @@ jobs:
         with:
           app-name: 'StarWarsLegionArmyBuilder-WebApp'
           slot-name: 'Production'
-          package: ./myapp
+          package: D:\a\_temp\myapp
